#Project Setup
general:
  productiveBranch: 'pipeline-try'

#Steps Specific Configuration
steps:
  executeMaven:
#    dockerImage: 'maven:3.5.0-jdk-8'
    projectSettingsFile : ''

  deployToNeoWithCli:
    dockerImage: 's4sdk/docker-neo-cli'

#Stage Specific Configurations
stages:
  staticCodeChecks:
    findbugsExcludesFile: '' #Path to findbugs exclude file
    pmdExcludes: '' # List or ANT style patterns

#  integrationTests:
#    credentials:
#      - alias: ''
#        credentialId: ''

#  s4SdkQualityChecks:
#    jacocoExcludes:
#      - ''
#    nonErpDestinations:
#      - ''

#  productionDeployment:
#    neoTargets:
#      - host: 'host'
#        account: 'yourAccount'
#        application: 'appName'
#        credentialsId: 'credentialsId'
